services:
  - type: web
    name: jarvis-ai-service
    env: static
    buildCommand: npm run build
    staticPublishPath: ./build
    routes:
      - type: rewrite
        source: /.*
        destination: /index.html